_wandb:
    value:
        cli_version: 0.25.0
        e:
            kfwwz3nw8rqtpfvnwwwhaamq8uxbxtcq:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: kadai3 /main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1995218165760"
                        used: "525022384128"
                email: s.tomita2023@keio.jp
                executable: /Users/tomita/lab/kenshu/.venv/bin/python3
                git:
                    commit: e9233763bb1fe627105d6704458e6c52c5f024bf
                    remote: https://github.com/SatoshiTomita/kenshu.git
                host: murata-labnoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-14.2.1-arm64-arm-64bit-Mach-O
                program: /Users/tomita/lab/kenshu/kadai3 /main.py
                python: CPython 3.13.12
                root: '/Users/tomita/lab/kenshu/kadai3 '
                startedAt: "2026-03-15T08:03:14.845924Z"
                writerId: kfwwz3nw8rqtpfvnwwwhaamq8uxbxtcq
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
config:
    value: '{''note'': ''cnn+rnn baseline(image_test,epoch50)''}'
train_name:
    value: cnn_rnn_baseline(gru_fix)
