mode: offline_test  # train | offline_test
train_name: cnn_gru_baseline(epoch150,hiddendeim256)
seed: 42
result_root: result

device: cpu  # auto | cpu | cuda | mps

wandb:
  enable: true
  project: kadai3
  run_name: ${train_name}
  config:
    note: cnn+rnn baseline(epoch150,state_noise0.1)

dataset:
  root: data
  train_dir: train
  test_dir: test
  left_dirname: left
  right_dirname: right
  variant: right_only  # right_only | both 入力データの切り替えに対応
  # concatenated blosc2 filenames
  action_states_filename: action_states.blosc2
  image_states_filename: image_states.blosc2
  joint_states_filename: joint_states.blosc2
  # fallback keys for npz/pt/pth (1 file = 1 episode)
  image_key: image
  state_key: state
  action_key: action
  seq_len: 8
  val_ratio: 0.2
  test_ratio: 0.2
  batch_size: 8
  num_workers: 0
  pin_memory: false
  # 画像データ拡張
  augment: true
  aug_brightness: 0.1
  aug_contrast: 0.1
  aug_shift: 4

# vision networkの各種設定
vision:
  in_channels: 3
  conv_channels: [32, 64, 128]
  kernels: [5, 3, 3]
  strides: [2, 2, 2]
  paddings: [2, 1, 1]
  feature_dim: 256

# policy networkの各種設定
policy:
  rnn_type: gru  # rnn | gru
  hidden_dim: 256
  num_layers: 1

# trainerの各種設定
trainer:
  epochs: 50
  learning_rate: 5e-4
  weight_decay: 1.0e-4
  grad_clip_norm: 1.0
  use_state: true
  state_noise_std: 0.05

replay:
  # replayを起動するかどうか
  enable: true
  model_path: "result/cnn_gru_baseline(epoch150,hiddendeim256)/best_model.pt"  # empty means result/<train_name>/best_model.pt
  steps: 150
  fps: 30
  ema: 0.0
  split: 100
  # テスト結果を実機に送るかどうか
  send_action: true  
  image_key: image.main
  state_key: observation.state
  max_depth: null
  init_from_current_state: false
  # Replay init params
  height: 360
  width: 640
  # Inference-time resize (set to null to disable)
  resize_height: 360
  resize_width: 640
  serial_numbers: []
  camera_id: [0]
  scale: 1.0
  auto_exposure: false
  auto_white_balance: false
  exposure: 190.0
  white_balance: 3300.0
  min_depth: 0.0
  max_depth_realsense: 1500.0
  is_higher_port: false
  leader_port: /dev/tty.usbmodem58370530001
  follower_port: /dev/tty.usbmodem58370529971
  calibration_name: koch

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
